FROM php:7-fpm

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /www

RUN apt-get update && apt-get install -my \
	wget \
	g++ \
	git \
	unzip \
	libgmp-dev \
	libicu-dev \
	libssh2-1 libssh2-1-dev \
	libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer global require "fxp/composer-asset-plugin:^1.2.0"

RUN	docker-php-source extract \
	&& docker-php-ext-install mysqli pdo_mysql zip intl \
    && docker-php-ext-enable intl \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install ftp \
    && wget https://github.com/Sean-Der/pecl-networking-ssh2/archive/php7.zip \
	&& unzip php7.zip \
	&& cd pecl-networking-ssh2-php7 \
	&& phpize \
	&& ./configure \
	&& make \
	&& make install \
    && docker-php-ext-enable ssh2 \
    && ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h \
    && docker-php-ext-install gmp

#Данную команду рекомендую всегда помещать в конец, так как конфиг php вероятно придется менять часто
COPY ./config/php.ini /usr/local/etc/php/